apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-k8s-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: NGINX_ENV
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: nginx_env