apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-k8s-demo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80